Force a become when removing docker mounted files
lawliet89/docker-compose-ansible pull request #6
Opened 2017-08-11 01:16 UTC by xkjyeah

Here's the problem

1. Mount some docker volume
2. Container writes files as root to docker volume
3. Script cannot clear out the files any more.

I'm not sure if this is the solution...

2017-08-11 04:47 UTC, lawliet89 requested changes

2017-08-11 04:47 UTC, lawliet89 commented on tasks/main.yml
> +  become: true
Paramaterise this with 

```
become: "{{ docker_become }}"
```
like how it's done elsewhere.

You also need to do this for the steps below this which clears directories.

2017-08-14 08:44 UTC, xkjyeah commented on tasks/main.yml
> +  become: true
Ok fixed

2017-08-14 08:44 UTC, lawliet89 approved these changes

2017-08-14 08:44 UTC, merged